sudo: required
dist: trusty
language: python
python:
    - 2.7
    - 3.4
    - 3.5

before_install:
    - sudo pip install pytest-cov

script:
    - py.test --cov=csirtgsdk --cov-fail-under=25

notifications:
    email:
        on_success: never
        on_failure: never
